### ISSUE TITLE
'NERLSTM_CRF' object has no attribute 'seg_size'

### ISSUE THREAD

**Issue by sjzryf** [DengYangyong/medical_entity_recognize#5]
您好，请教一下这个报错是什么原因，谢谢！
2020-06-24 16:39:36,590 - main.py - train - INFO - 101218 / 7827 / 16804 sentences in train / dev / test.
Traceback (most recent call last):
  File "main.py", line 201, in <module>
    train()
  File "main.py", line 51, in train
    model = NERLSTM_CRF(config, char_to_id, tag_to_id, emb_matrix)
  File "/home/ryf/Desktop/medical_entity_recognize-master/model/LSTM_CRF.py", line 21, in __init__
    self.seg_size, config.seg_dim, padding_idx=0
  File "/home/ryf/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'NERLSTM_CRF' object has no attribute 'seg_size'

**Comment by sjzryf** [comment]
没问题了，代码里拼错了

**Comment by DengYangyong** [comment]
对，写成 self.seg_dize了，无语...
谢谢哈，已经改了
